org: arghajeetbhattacharya
service: my-express--serverless-application

provider:
  name: aws
  runtime: nodejs10.x
  stage: dev
  region: ap-south-1

functions:
  app:
    handler: server.handler
    events:
      - http:
          path: /api/hello
          method: GET
          cors: true
      - http:
          path: /api/get-value/{proxy+}
          method: GET
          cors: true
      - http:
          path: /api/get-user-list
          method: GET
          cors: true
